-- noinspection SqlNoDataSourceInspectionForFile

CREATE TABLE SYSTEM.IMC(
    imcId NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 NOCACHE) PRIMARY KEY,
    height NUMBER NOT NULL,
    weight NUMBER NOT NULL,
    imc NUMBER NOT NULL
);
